ANDROID: Resolve header conflicts in userfaultfd syscall tests
Fixes the following compilation errors in external/ltp:
* error: redefinition of 'uffdio_move'
* error: redefinition of 'uffdio_writeprotect'

These structures are provided by bionic/libc/kernel/uapi/linux/userfaultfd.h.
Explicitly added the following flags to Android.bp to skip LTP's internal LAPI definitions:
- HAVE_STRUCT_MNT_ID_REQ_MNT_NS_FD
- HAVE_STRUCT_UFFDIO_MOVE
- HAVE_STRUCT_UFFDIO_WRITEPROTECT

Test: local

Bug: 493476605
Change-Id: I68d9a476e7a583e9fbc00f58b1c88bb5c927832f
Signed-off-by: Steve Liao <steveliao@google.com>